<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <AvaloniaResource Include="Fonts\*.ttf" />
    <AvaloniaResource Include="Assets\*.ico" />
    <None Update="Fonts\OFL.txt" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaXaml Include="../../teknesyum-ui/ustcubuk/*.axaml" Link="Kabuk/%(Filename)%(Extension)" />
    <Compile Include="../../teknesyum-ui/ustcubuk/*.cs" Link="Kabuk/%(Filename)%(Extension)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AbxPilot.Core\AbxPilot.Core.csproj" />
    <ProjectReference Include="..\AbxPilot.Data\AbxPilot.Data.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="$(AvaloniaVersion)" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="$(AvaloniaVersion)" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="$(CommunityToolkitMvvmVersion)" />
  </ItemGroup>

</Project>
