<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AssemblyName>AbxPilot</AssemblyName>
    <ApplicationIcon>..\AbxPilot.UI\Assets\abxpilot.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\AbxPilot.UI\Assets\abxpilot.ico" Link="abxpilot.ico" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AbxPilot.UI\AbxPilot.UI.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Desktop" Version="$(AvaloniaVersion)" />
  </ItemGroup>

</Project>
